### ISSUE TITLE
Project has multiple vulnerabilities across its dependencies

### ISSUE THREAD

**Issue by artyom** [Doist/IDBStorage#3]
Github has been sending these security alerts for months:

<img width="528" alt="Screen Shot 2020-03-03 at 12 03 17" src="https://user-images.githubusercontent.com/68182/75759656-fce23b00-5d46-11ea-8dc4-635c09047b51.png">

**Comment by stkao05** [comment]
Addressed [here](https://github.com/Doist/IDBStorage/commit/ce502cd73185304a25de41b7069a8597363fc2b2). Thanks for pinging @artyom
