### ISSUE TITLE
Filter / query by object property?

### ISSUE THREAD

**Issue by pwFoo** [Doist/IDBStorage#30]
Hi,
I searching for a small solution with query / filter option to find / get items by a property value instead only the key.
Is it possible to add that feature which indexeddb do with "index"?

**Comment by henningmu** [comment]
Hi @pwFoo,
we currently have no intentions of adding this feature. If you really want it, I recommend forking IDBStorage and adding it there 👍

**Comment by pwFoo** [comment]
@henningmu thanks for quick answer 👍
